### PR TITLE
Iss41 add npm scripts

### PR DESCRIPTION
**Pull request by Pencraft**

### CODE REVIEW

**Comment by forrestsill** [comment]
Does anyone know what's up with this PR? Can it be closed?

**Comment by Pencraft** [comment]
I had written scripts to automate our tests, much like the TA requested, but nobody ever merged them. :/

**Comment by forrestsill** [comment]
Oooh okay. Are they still worth merging do you think? @afreymiller ?

**Comment by anandnk24** [comment]
Yeah, I think you should merge them anyway! We can discuss this with the TA.  





On Tue, Mar 7, 2017 2:28 PM, Forrest Sill notifications@github.com  wrote:
Oooh okay. Are they still worth merging do you think? @afreymiller  ?

**Pull request closed without merging**
